### ISSUE TITLE
Question about the execute()-function

### ISSUE THREAD

**Issue by SjorsKeuninkx** [bricev/JobQueue#2]
Hello,

i'm using your package to queue items to handle them sequently. But in the class AbstractJob, there is a execute()-function defined. This function is called in the Worker-class.

When I'm running a queued item, I always see an error was triggered. You can see the snapshot:

[2015-05-06 10:00:41] development.web.ERROR: Worker 'packer-parallels-iso:dummy (5549ca27047eb)' encountered an error with Task '2' ["Impossible to perform the Job",0] []

But I'm sure the task is already executed. 

Could you tell me, this code section is unfinished? Or what is the reason to use a switch(false)-statement.

I also tried to remove an already executed task. Is it better to write a cronjob which will check all tasks or is there an easier way?

I hope to hear from you

**Comment by bricev** [comment]
Hi!

You should define everything your Jobs have to do in the `perform()` method. Eventually, if you have stuff you want to do before and after the main work, you have two convenient methods walled `setup()` and `terminate()` that could optionally used to organize your Job properly. 

Anyway, all of those 3 methods (perform, setup and terminate) **HAVE** to return true to let `execute()` method understand that the job has been well done.

The error you get comes from the fact perform() method from your Job does not return `true`.

**Comment by SjorsKeuninkx** [comment]
Hi,

thanks for your quick reply. I'm gonna try some things.

If I have any further question, I will reopen this issue.
