### ISSUE TITLE
Problem while removing queued task

### ISSUE THREAD

**Issue by SjorsKeuninkx** [bricev/JobQueue#3]
Good afternoon,

last week I used your package further to implement a queue system. After my first question, you helped me out to continue, but there's something wrong.

When I'm trying to delete a task using PHP-code (so I'm not using the console command), an error was thrown. It shows me getStatus() was called on an unknown object. After a lot of debugging, I concluded the Task object was 'transformed' to an QueueFactory-object. 

How is this possible?

The above example was triggered while using the terminate()-function. This function was returning true. For now, I've implemented a workaround, but I'll hope you can fix the problem.

Yours sincerely,
Sjors Keuninkx

**Comment by bricev** [comment]
The proper way to delete a Task from the Queue is to execute the following code
```php
/* @var $queue QueueInterface */
/* @var $task Task */
$queue->delete($task);
```

Could you show me your code?

**Comment by SjorsKeuninkx** [comment]
Below you will find my code

```php
class EmailJob extends AbstractJob implements JobInterface
{

    public function perform()
    {
        $mailer = new Mailer();
        $mailer->setUseNoReply($this->getParameter('useNoReply'));
        $mailer->setPort($this->getParameter('port'));
        $mailer->sendEmail($this->getParameter('data'));

        return true;
    }

    public function terminate()
    {
        $queue = $this->getQueue();
        $task = $this->getTask();

        $queue->delete($task);

        return true;
    }

}
```

**Comment by bricev** [comment]
Ok, I get it now :)
Tasks are not meant to be deleted during their own `Job` performance.
The way I use it, I let Tasks in Redis (this does not take much in memory anyway) when finished because I need to be able to track Tasks in the future. 

My advise: you should have a cron script that cleans `finished` Jobs periodically. 
Something like:
```php
/* @var $queue QueueInterface */
foreach ($queue->getTasks('your-profile', Task::STATUS_FINISHED) as $task) {
    /* @var $task Task */
    $queue->delete($task);
}
```

**Comment by SjorsKeuninkx** [comment]
Alright, thanks for your help.
I also considered a cronjob, but I thought there was also another opportunity.
