### ISSUE TITLE
RedisQueue

### ISSUE THREAD

**Issue by 15921050052** [bricev/JobQueue#4]
at line 172
$this->getClient()->lrem($source, 0, $persistedTask->getId());
should be 
$this->getClient()->lrem($source,  $persistedTask->getId(),0);

**Comment by bricev** [comment]
Sorry but I'm not convinced about that:
The idea is to remove all (count = 0) Tasks from the list having `$persistedTask->getId()` as value.
According to the doc (http://redis.io/commands/lrem) command should look like this:
```
 LREM key count value 
```
And Predis client reflects the Redis command patterns.
Are you OK with my answer?

**Comment by 15921050052** [comment]
I know the purpose
It seems some doc is wrong.
I reviewed the phpredis doc https://github.com/phpredis，
LREM key  value count
And checked the code 
https://github.com/nrk/predis/blob/v1.0/src/ClientInterface.php
 * @method int    lrem($key, $count, $value)
I found in  my ENV，the running task id is not remove when the task finished.
